---

- name: Create directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  with_items:
    - "{{ openssl_ca_folders }}"

- name: Check if db.index exists
  ansible.builtin.stat:
    path: "{{ openssl_ca_base_path }}/db.index"
  register: db_index

- name: Create db.index
  ansible.builtin.file:
    path: "{{ openssl_ca_base_path }}/db.index"
    state: touch
  when: not db_index.stat.exists

- name: Check if db.serial exists
  ansible.builtin.stat:
    path: "{{ openssl_ca_base_path }}/db.serial"
  register: db_serial

- name: Create db.serial
  ansible.builtin.template:
    src: db.serial.j2
    dest: "{{ openssl_ca_base_path }}/db.serial"
    mode: '0700'
  when: not db_serial.stat.exists

- name: Configure CA (root)
  ansible.builtin.template:
    src: "{{ openssl_ca_cnf_file }}.j2"
    dest: "{{ openssl_ca_base_path }}/{{ openssl_ca_cnf_file }}"
    mode: 0644

- name: Configure CA (server)
  ansible.builtin.template:
    src: "{{ openssl_server_cnf_file }}.j2"
    dest: "{{ openssl_ca_base_path }}/{{ openssl_server_cnf_file }}"
    mode: 0644

- name: Create CA key and CSR
  ansible.builtin.command: |
    openssl req
    -x509
    -config {{ openssl_ca_base_path }}/{{ openssl_ca_cnf_file }}
    -newkey rsa:4096
    -sha256
    -out {{ openssl_ca_base_path }}/{{ openssl_ca_root_certificate }}
    -outform PEM
    -passout pass:{{ openssl_ca_root_private_key_passphrase }}
    -batch
    -days {{ openssl_ca_root_days }}
  args:
    creates: "{{ openssl_ca_base_path }}/{{ openssl_ca_root_private_key }}"
    chdir: "{{ openssl_ca_base_path }}"

- name: Configure CA (key/csr script)
  ansible.builtin.template:
    src: openssl_generate_private_key.sh.j2
    dest: "{{ openssl_ca_base_path }}/openssl_generate_private_key.sh"
    mode: 0744

- name: Configure CA (signing script)
  ansible.builtin.template:
    src: openssl_sign.sh.j2
    dest: "{{ openssl_ca_base_path }}/openssl_sign.sh"
    mode: 0744

- name: Deploy CA README
  ansible.builtin.template:
    src: README.md.j2
    dest: "{{ openssl_ca_base_path }}/README.md"
    mode: 0644
